[package]
name = "sl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.1.8"
owo-colors = "3"
flexi_logger = "0.23"
log = "0.4"
ctrlc = "3.2.5"
dirs = "4.0"
